import type { Decision, Document, FeeLine, Person, Risk, StageId, Week } from "./types";

export const project = {
  code: "ERA-HV-26-014",
  name: "Harrow & Vale LLP",
  subtitle: "Farringdon HQ · CAT B fit-out",
  address: "14 Saffron Hill, EC1N 8XA",
  areaSqft: 18400,
  contract: "JCT Traditional 2016",
  programmeWeeks: 14,
  stage: "strategic" as StageId,
  stageLabel: "Strategic Definition · RFP close",
  client: "Harrow & Vale LLP",
  sponsor: "Amelia Croft",
  sponsorTitle: "Head of Real Estate",
  certainty: 4125000,
  certaintyBand: 0.06,
  previousCertainty: 4190000,
  contingency: 185000,
  feesTotal: 168750,
  onSite: "12 Oct 2026",
  handover: "18 Jan 2027",
};

export const stages: { id: StageId; n: string; label: string }[] = [
  { id: "lease", n: "00", label: "Lease" },
  { id: "strategic", n: "01", label: "Strategic" },
  { id: "brief", n: "02", label: "Brief" },
  { id: "design", n: "03", label: "Design" },
  { id: "procure", n: "04", label: "Procure" },
  { id: "construct", n: "05", label: "Construct" },
  { id: "handover", n: "06", label: "Handover" },
];

export const people: Person[] = [
  {
    id: "de",
    name: "David Evans",
    role: "Director, Project Management",
    org: "ERA",
    lens: "era",
    initials: "DE",
  },
  {
    id: "hg",
    name: "Henry Geldenhuys",
    role: "Director, Cost Consultancy",
    org: "ERA",
    lens: "era",
    initials: "HG",
  },
  {
    id: "ac",
    name: "Amelia Croft",
    role: "Head of Real Estate",
    org: "Harrow & Vale LLP",
    lens: "client",
    initials: "AC",
  },
  {
    id: "jl",
    name: "James Lang",
    role: "Managing Partner",
    org: "Harrow & Vale LLP",
    lens: "client",
    initials: "JL",
  },
  {
    id: "sk",
    name: "Saira Khan",
    role: "Landlord solicitor",
    org: "Pritchard Hale",
    lens: "restricted",
    initials: "SK",
  },
  {
    id: "mt",
    name: "Marcus Teale",
    role: "Design lead",
    org: "Studio North",
    lens: "guest",
    initials: "MT",
  },
];

export const fees: FeeLine[] = [
  {
    id: "f1",
    item: "Project management",
    basis: "2.75% of construction (capped)",
    amount: 113438,
    status: "issued",
    namedTo: "David Evans",
  },
  {
    id: "f2",
    item: "Cost consultancy",
    basis: "Fixed fee through PC",
    amount: 42000,
    status: "issued",
    namedTo: "Henry Geldenhuys",
  },
  {
    id: "f3",
    item: "Landlord licence pack",
    basis: "Fixed, time-boxed",
    amount: 6500,
    status: "draft",
    namedTo: "David Evans",
  },
  {
    id: "f4",
    item: "Post-handover thrive (12 weeks)",
    basis: "Optional retainer",
    amount: 6812,
    status: "draft",
    namedTo: "David Evans",
  },
];

export const decisions: Decision[] = [
  {
    id: "d1",
    title: "Procurement route",
    body: "JCT Traditional selected over Design & Build to retain design authorship for the partners’ floor and control of the hospitality-grade reception.",
    status: "certified",
    feeNamed: null,
    namedBy: "Amelia Croft",
    certifiedBy: "David Evans",
    at: "2026-07-28",
    aiDraft: false,
  },
  {
    id: "d2",
    title: "Fee proposal — PM + Cost",
    body: "PM at 2.75% capped against the £4.125m cost plan. Cost consultancy as a fixed £42,000 through practical completion. Named to Evans and Geldenhuys.",
    status: "certified",
    feeNamed: "£155,438",
    namedBy: "Henry Geldenhuys",
    certifiedBy: "Amelia Croft",
    at: "2026-08-04",
    aiDraft: false,
  },
  {
    id: "d3",
    title: "Cat B quality band",
    body: "Partners’ floor and client suite at upper-quartile finish; remainder at mid-quartile. Protects the £4.125m ceiling without flattening the brief.",
    status: "open",
    feeNamed: null,
    namedBy: "Marcus Teale",
    certifiedBy: null,
    at: "2026-08-12",
    aiDraft: false,
  },
  {
    id: "d4",
    title: "Landlord licence programme",
    body: "Draft pack ready for Pritchard Hale. AI assembled the schedule of condition index — unsigned, awaiting Evans.",
    status: "countered",
    feeNamed: "£6,500",
    namedBy: "Draft desk",
    certifiedBy: null,
    at: "2026-08-14",
    aiDraft: true,
  },
];

export const documents: Document[] = [
  {
    id: "doc1",
    title: "Strategic brief — space, budget, programme, quality",
    kind: "Brief",
    rev: "C",
    stamp: "issued",
    pages: 18,
    updated: "11 Aug 2026",
    owner: "David Evans",
    summary:
      "Translates Harrow & Vale’s partnership model into 18,400 sq ft: client suite, two courts of meeting, quiet floor, hospitality reception.",
  },
  {
    id: "doc2",
    title: "Fee proposal — named people, named fees",
    kind: "Commercial",
    rev: "B",
    stamp: "certified",
    pages: 6,
    updated: "4 Aug 2026",
    owner: "Henry Geldenhuys",
    summary:
      "Certified by Amelia Croft. PM capped. Cost consultancy fixed. No public link. Watermarked to the named reader.",
  },
  {
    id: "doc3",
    title: "Cost plan 01 — elemental",
    kind: "Cost",
    rev: "01",
    stamp: "issued",
    pages: 11,
    updated: "8 Aug 2026",
    owner: "Henry Geldenhuys",
    summary:
      "£4.125m including £185k contingency. Variance −£65k versus first pass after value engineering the secondary staircase.",
  },
  {
    id: "doc4",
    title: "Landlord licence — draft pack",
    kind: "Legal",
    rev: "A",
    stamp: "draft",
    pages: 22,
    updated: "14 Aug 2026",
    owner: "Draft desk",
    summary:
      "Assembled by draft AI from the brief and schedule of condition. Not certified. Internal notes hidden from the landlord solicitor.",
  },
  {
    id: "doc5",
    title: "Programme — 14 weeks on site",
    kind: "Programme",
    rev: "B",
    stamp: "issued",
    pages: 3,
    updated: "9 Aug 2026",
    owner: "David Evans",
    summary: "Strip-out week 1–2. First fix 3–6. Second fix 7–10. Commission and soft landing 11–14.",
  },
  {
    id: "doc6",
    title: "Internal cost note — risk on stone",
    kind: "Note",
    rev: "—",
    stamp: "internal",
    pages: 1,
    updated: "13 Aug 2026",
    owner: "Henry Geldenhuys",
    summary: "Italian stone lead time. ERA-only. Never leaves the record.",
  },
];

export const weeks: Week[] = [
  { id: 1, label: "W01", phase: "Strip-out", note: "Soft strip, services isolation", status: "later" },
  { id: 2, label: "W02", phase: "Strip-out", note: "Asbestos clearance hold point", status: "later" },
  { id: 3, label: "W03", phase: "First fix", note: "Partitions, containment", status: "later" },
  { id: 4, label: "W04", phase: "First fix", note: "MEP mains", status: "later" },
  { id: 5, label: "W05", phase: "First fix", note: "Staircase steel", status: "later" },
  { id: 6, label: "W06", phase: "First fix", note: "Ceiling grid", status: "later" },
  { id: 7, label: "W07", phase: "Second fix", note: "Joinery, stone", status: "later" },
  { id: 8, label: "W08", phase: "Second fix", note: "Partner floor", status: "later" },
  { id: 9, label: "W09", phase: "Second fix", note: "AV / acoustics", status: "later" },
  { id: 10, label: "W10", phase: "Second fix", note: "Furniture install", status: "later" },
  { id: 11, label: "W11", phase: "Commission", note: "Test and witness", status: "later" },
  { id: 12, label: "W12", phase: "Commission", note: "Client snag", status: "later" },
  { id: 13, label: "W13", phase: "Soft landing", note: "Staff induction", status: "later" },
  { id: 14, label: "W14", phase: "Handover", note: "PC and thrive start", status: "later" },
];

export const risks: Risk[] = [
  {
    id: "r1",
    title: "Landlord licence decision sitting with solicitor",
    severity: "hold",
    owner: "Saira Khan",
    note: "Pack is draft. Cannot issue until Evans certifies the AI index.",
  },
  {
    id: "r2",
    title: "Stone lead time versus week 7",
    severity: "watch",
    owner: "Henry Geldenhuys",
    note: "Internal. Alternative specified if order not placed by 1 Sept.",
  },
  {
    id: "r3",
    title: "Quality band still open on partners’ floor",
    severity: "risk",
    owner: "Amelia Croft",
    note: "Uncertified decision. Holds the cost ceiling.",
  },
];

export const briefClauses = [
  {
    id: "b1",
    pillar: "Space",
    title: "18,400 sq ft over two floors",
    copy: "Client suite and two courts of meeting on 4. Quiet floor and knowledge work on 5. Hospitality reception that can host a 40-cover supper.",
  },
  {
    id: "b2",
    pillar: "Budget",
    title: "£4.125m cost ceiling",
    copy: "Including £185k contingency. Upper-quartile finish only where a partner or client will feel it. Mid-quartile elsewhere.",
  },
  {
    id: "b3",
    pillar: "Programme",
    title: "14 weeks on site, lease from 1 Oct",
    copy: "On site 12 October. Practical completion 18 January. Phased staff return from week 13.",
  },
  {
    id: "b4",
    pillar: "Quality",
    title: "Boutique, not corporate",
    copy: "Hospitality-grade reception. Timber and stone, not brand-standard grey. Acoustic privacy for the courts.",
  },
];
